src/Entity/WikiPage.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Pagerfanta\Adapter\DoctrineSelectableAdapter;
use Pagerfanta\Pagerfanta;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WikiPageRepository")
 * @ORM\Table(uniqueConstraints={
 *     @ORM\UniqueConstraint(name="wiki_pages_path_idx", columns={"path"}),
 *     @ORM\UniqueConstraint(name="wiki_pages_normalized_path_idx", columns={"normalized_path"}),
 * })
 */
class WikiPage {
    /**
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue()
     * @ORM\Id()
     *
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string|null
     */
    private $path;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string|null
     */
    private $normalizedPath;

    /**
     * @ORM\OneToMany(targetEntity="WikiRevision", mappedBy="page", cascade={"persist", "remove"})
     *
     * @var WikiRevision[]|Collection
     */
    private $revisions;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $locked = false;

    public function __construct(
        string $path,
        string $title,
        string $body,
        User $user,
        \DateTime $timestamp = null
    ) {
        $this->setPath($path);
        $this->revisions = new ArrayCollection();

        new WikiRevision($this, $title, $body, $user, $timestamp);
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getPath(): string {
        return $this->path;
    }

    public function setPath(string $path): void {
        $this->path = $path;
        $this->normalizedPath = self::normalizePath($path);
    }

    public function getNormalizedPath(): string {
        return $this->normalizedPath;
    }

    /**
     * @return Collection|WikiRevision[]
     */
    public function getRevisions(): Collection {
        return $this->revisions;
    }

    public function getLatestRevision(): WikiRevision {
        $criteria = Criteria::create()
            ->orderBy(['timestamp' => 'DESC'])
            ->setMaxResults(1);

        return $this->revisions->matching($criteria)->first();
    }

    public function addRevision(WikiRevision $revision): void {
        if (!$this->revisions->contains($revision)) {
            $this->revisions->add($revision);
        }
    }

    /**
     * @return Pagerfanta|WikiRevision[]
     */
    public function getPaginatedRevisions(int $page, int $maxPerPage = 25): Pagerfanta {
        $criteria = Criteria::create()->orderBy(['timestamp' => 'DESC']);

        $revisions = new Pagerfanta(new DoctrineSelectableAdapter($this->revisions, $criteria));
        $revisions->setMaxPerPage($maxPerPage);
        $revisions->setCurrentPage($page);

        return $revisions;
    }

    public function isLocked(): bool {
        return $this->locked;
    }

    public function setLocked(bool $locked): void {
        $this->locked = $locked;
    }

    public static function normalizePath(string $path): string {
        return strtolower(str_replace('-', '_', $path));
    }
}

src/Form/WikiType.php
<?php

namespace App\Form;

use App\Form\Model\WikiData;
use App\Form\Type\MarkdownType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WikiType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void {
        $builder
            ->add('title', TextType::class, [
                'label' => 'label.title',
            ])
            ->add('body', MarkdownType::class, [
                'label' => 'label.body',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void {
        $resolver->setDefaults([
            'data_class' => WikiData::class,
        ]);
    }
}

src/Controller/WikiController.php
<?php

namespace App\Controller;

use App\Entity\WikiPage;
use App\Entity\WikiRevision;
use App\Form\Model\WikiData;
use App\Form\WikiType;
use App\Repository\WikiPageRepository;
use App\Repository\WikiRevisionRepository;
use App\Utils\Differ;
use Doctrine\ORM\EntityManagerInterface;
use Ramsey\Uuid\Uuid;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @IsGranted("view_wiki", statusCode=404)
 */
final class WikiController extends AbstractController {
    /**
     * Views a wiki page.
     */
    public function wiki(string $path, WikiPageRepository $wikiPageRepository): Response {
        $page = $wikiPageRepository->findOneCaseInsensitively($path);

        if (!$page) {
            return $this->render('wiki/404.html.twig', [
                'path' => $path,
            ], new Response('', 404));
        }

        return $this->render('wiki/page.html.twig', [
            'page' => $page,
        ]);
    }

    /**
     * Creates a wiki page.
     *
     * @IsGranted("ROLE_USER")
     *
     * @todo handle conflicts
     * @todo do something if the page already exists
     */
    public function create(Request $request, string $path, EntityManagerInterface $em): Response {
        $data = new WikiData();

        $form = $this->createForm(WikiType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $page = $data->toPage($path, $this->getUser());

            $em->persist($page);
            $em->flush();

            return $this->redirectToRoute('wiki', ['path' => $path]);
        }

        return $this->render('wiki/create.html.twig', [
            'form' => $form->createView(),
            'path' => $path,
        ]);
    }

    /**
     * @Entity("page", expr="repository.findOneCaseInsensitively(path)")
     * @IsGranted("ROLE_USER")
     * @IsGranted("delete", subject="page", statusCode=403)
     */
    public function delete(Request $request, WikiPage $page, EntityManagerInterface $em): Response {
        $this->validateCsrf('wiki_delete', $request->request->get('token'));

        $em->remove($page);
        $em->flush();

        $this->addFlash('success', 'flash.wiki_page_deleted');

        return $this->redirectToRoute('wiki');
    }

    /**
     * Edits a wiki page.
     *
     * @Entity("page", expr="repository.findOneCaseInsensitively(path)")
     * @IsGranted("ROLE_USER")
     * @IsGranted("write", subject="page", statusCode=403)
     *
     * @todo handle conflicts
     */
    public function edit(Request $request, WikiPage $page, EntityManagerInterface $em): Response {
        $data = WikiData::createFromPage($page);
        $form = $this->createForm(WikiType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updatePage($page, $this->getUser());

            $em->flush();

            return $this->redirectToRoute('wiki', [
                'path' => $page->getPath(),
            ]);
        }

        return $this->render('wiki/edit.html.twig', [
            'form' => $form->createView(),
            'page' => $page,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("lock", subject="page", statusCode=403)
     */
    public function lock(Request $request, WikiPage $page, bool $lock, EntityManagerInterface $em): Response {
        $this->validateCsrf('wiki_lock', $request->request->get('token'));

        $page->setLocked($lock);

        $em->flush();

        $this->addFlash('success', 'flash.page_'.($lock ? 'locked' : 'unlocked'));

        if ($request->headers->has('Referer')) {
            return $this->redirect($request->headers->get('Referer'));
        }

        return $this->redirectToRoute('wiki', ['path' => $page->getPath()]);
    }

    /**
     * @Entity("wikiPage", expr="repository.findOneCaseInsensitively(path)")
     */
    public function history(WikiPage $wikiPage, int $page): Response {
        return $this->render('wiki/history.html.twig', [
            'page' => $wikiPage,
            'revisions' => $wikiPage->getPaginatedRevisions($page),
        ]);
    }

    public function diff(Request $request, WikiRevisionRepository $repository): Response {
        /* @var WikiRevision $from
         * @var WikiRevision $to */
        [$from, $to] = array_map(function ($q) use ($request, $repository) {
            $id = $request->query->get($q);

            if (!Uuid::isValid($id)) {
                throw $this->createNotFoundException();
            }

            $revision = $repository->find($id);

            if (!$revision) {
                throw $this->createNotFoundException();
            }

            return $revision;
        }, ['from', 'to']);

        if ($from->getPage() !== $to->getPage()) {
            throw $this->createNotFoundException('Tried to compare two different pages');
        }

        return $this->render('wiki/diff.html.twig', [
            'diff' => Differ::diff($from->getBody(), $to->getBody()),
            'from' => $from,
            'to' => $to,
            'page' => $from->getPage(),
        ]);
    }

    public function revision(WikiRevision $revision): Response {
        return $this->render('wiki/revision.html.twig', [
            'page' => $revision->getPage(),
            'revision' => $revision,
        ]);
    }

    public function all(int $page, WikiPageRepository $wikiPageRepository): Response {
        $pages = $wikiPageRepository->findAllPages($page);

        return $this->render('wiki/all.html.twig', [
            'pages' => $pages,
        ]);
    }

    public function recentChanges(WikiRevisionRepository $repository, int $page): Response {
        return $this->render('wiki/recent.html.twig', [
            'revisions' => $repository->findRecent($page),
        ]);
    }
}

templates/wiki/404.html.twig
{% extends 'wiki/base.html.twig' %}

{% block site_nav_active 'places' %}
{% block site_nav_main_menu_active 'wiki' %}

{% block title %}
  {{ 'wiki.not_found_title'|trans }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <p>{{ 'wiki.not_found_message'|trans }}</p>

  {% if is_granted('ROLE_USER') %}
    <p>
      <a href="{{ path('wiki_create', {path: path}) }}" class="button">
        {{- 'wiki.create_this_page'|trans -}}
      </a>
    </p>
  {% endif %}
{% endblock %}

templates/wiki/_form.html.twig
{% from '_macros/form.html.twig' import button_row %}

{{ form_start(form) }}
  {{ form_row(form.title) }}

  {{ form_row(form.body, {attr: {rows: 16}}) }}

  {{ button_row('action.save'|trans) }}
{{ form_end(form) }}

templates/wiki/all.html.twig
{% extends 'wiki/base.html.twig' %}

{% block site_nav_active 'places' %}
{% block site_nav_main_menu_active 'wiki' %}

{% block title 'wiki.all_pages'|trans %}

{% block head %}
  <link rel="canonical" href="{{ path('wiki_all') }}">

  {{ include('_includes/meta_pagination.html.twig', { pager: pages }, with_context=false) }}
{% endblock head %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {% embed '_layouts/table_pagination.html.twig' with { items: pages } %}
    {% block header %}
      <th class="table__shrink">{{ 'wiki.path'|trans }}</th>
      <th>{{ 'wiki.page_title'|trans }}</th>
    {% endblock header %}

    {% block row %}
      <td class="table__shrink"><a href="{{ path('wiki', {path: item.path}) }}">{{ item.path }}</a></td>
      <td>{{ item.latestRevision.title }}</td>
    {% endblock row %}
  {% endembed %}
{% endblock body %}

templates/wiki/base.html.twig
{% extends 'base.html.twig' %}

{% block wiki_nav_toolbox_active app.request.attributes.get('_route') %}

{% block sidebar %}
  <section class="sidebar__section sidebar-card">
    <h1 class="sidebar__title">{{ 'wiki.navigation'|trans }}</h1>

    <ul class="no-margin unlistify sidebar__no-padding">
      <li>
        <a href="{{ path('wiki_all') }}"
           class="menu-item {{ block('wiki_nav_toolbox_active') == 'wiki_all' ? 'menu-item--active' }}">
          {{- 'wiki.all_pages'|trans -}}
        </a>
      </li>
      <li>
        <a href="{{ path('wiki_recent_changes') }}"
           class="menu-item {{ block('wiki_nav_toolbox_active') == 'wiki_recent_changes' ? 'menu-item--active' }}">
          {{- 'label.recent_changes'|trans -}}
        </a>
      </li>
    </ul>
  </section>
{% endblock %}

templates/wiki/create.html.twig
{% extends 'base.html.twig' %}

{% block site_nav_active 'places' %}
{% block site_nav_main_menu_active 'wiki' %}

{% block title %}
  {{ 'wiki.create_title'|trans({'%path%': path}) }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {% include 'wiki/_form.html.twig' with {form: form} only %}
{% endblock %}

templates/wiki/diff.html.twig
{% extends 'wiki/page.html.twig' %}

{% block site_nav_active 'places' %}
{% block site_nav_main_menu_active 'wiki' %}
{% block wiki_page_toolbox_active 'wiki_history' %}

{% block title 'title.wiki_diff'|trans({
  'from': from.id[0:8],
  'to': to.id[0:8],
}) %}

{% block body %}
  {% from '_macros/time.html.twig' import relative_time, relative_time_diff %}
  <h1 class="page-heading">
    {{ 'title.wiki_diff'|trans({
      '%from%': '<a href="%s">%s</a>'|format(
        path('wiki_revision', {id: from.id})|e,
        from.id[0:8]
      ),
      '%to%': '<a href="%s">%s</a>'|format(
        path('wiki_revision', {id: to.id})|e,
        to.id[0:8]
      )
    })|raw }}
  </h1>

  <table class="diff-table">
    <thead>
    <tr>
      <th class="diff-table__header diff-table__header--from" colspan="2">
        {{ relative_time(from.timestamp) }}
      </th>
      <th class="diff-table__header diff-table__header--to" colspan="2">
        {{ relative_time_diff(to.timestamp, from.timestamp) }}
      </th>
    </tr>
    </thead>
    <tbody class="diff-table__line-group">
    {% with { lastOldLineNo: 0, lastNewLineNo: 0 } %}
      {% for entry in diff %}
        {% if not loop.first and
            (entry.oldLineNo ?? lastOldLineNo) != lastOldLineNo + 1 and
            (entry.newLineNo ?? lastNewLineNo) != lastNewLineNo + 1 %}
          </tbody><tbody class="diff-table__line-group">
        {% endif %}

        {% set lastOldLineNo = entry.oldLineNo ?? lastOldLineNo %}
        {% set lastNewLineNo = entry.newLineNo ?? lastNewLineNo %}

        <tr>
          {% if entry.oldLineNo is defined %}
            <th class="diff-table__line-no diff-table__line-no--{{ entry.type }}">{{ entry.oldLineNo }}</th>
            <td class="diff-table__content diff-table__content--{{ entry.type }}"><code>{{ entry.old }}</code></td>
          {% else %}
            <td class="diff-table__col-spacer" colspan="2"></td>
          {% endif %}

          {% if entry.newLineNo is defined %}
            <th class="diff-table__line-no diff-table__line-no--{{ entry.type }}">{{ entry.newLineNo }}</th>
            <td class="diff-table__content diff-table__content--{{ entry.type }}"><code>{{ entry.new }}</code></td>
          {% else %}
            <td class="diff-table__col-spacer" colspan="2"></td>
          {% endif %}
        </tr>
      {% endfor %}
    {% endwith %}
    </tbody>
  </table>
{% endblock %}

templates/wiki/edit.html.twig
{% extends 'wiki/page.html.twig' %}

{% block title %}
  {{ 'wiki.editing_title'|trans({'%path%': page.path}) }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ 'wiki.editing_title'|trans({
    '%path%': '<a href="%s">%s</a>'|format(path('wiki', {path: page.path})|escape, page.path|escape)
  })|raw }}</h1>

  {% include 'wiki/_form.html.twig' with {form: form} only %}
{% endblock %}

templates/wiki/history.html.twig
{% extends 'wiki/page.html.twig' %}

{% block title 'wiki.history_title'|trans({'%path%': page.path}) %}

{% block head %}
  {{ include('_includes/meta_pagination.html.twig', {pager: revisions}, with_context=false) }}
{% endblock head %}

{% block body %}
  <h1 class="page-heading">{{ 'wiki.history_title'|trans({
    '%path%': '<a href="%s">%s</a>'|format(path('wiki', {path: page.path})|escape, page.path|escape)
  })|raw }}</h1>

  <form action="{{ path('wiki_diff') }}">
    {% embed '_layouts/table_pagination.html.twig' with { items: revisions } %}
      {% block header %}
        <th class="table__shrink" colspan="2">{{ 'label.compare'|trans }}</th>
        <th class="table__shrink">{{ 'wiki.id_label'|trans }}</th>
        <th class="table__shrink">{{ 'wiki.revision_time'|trans }}</th>
        <th>{{ 'wiki.user'|trans }}</th>
      {% endblock header %}

      {% block row %}
        {% from '_macros/form.html.twig' import radio %}
        {% from '_macros/time.html.twig' import relative_time %}

        <td class="table__shrink">
          {{ radio({ name: 'from', value: item.id, checked: loop.index == 2 }) }}
        </td>
        <td class="table__shrink">
          {{ radio({ name: 'to', value: item.id, checked: loop.index == 1 }) }}
        </td>
        <td class="table__shrink">
          <a href="{{ path('wiki_revision', {id: item.id}) }}">{{ item.id.hex|slice(0, 8) }}</a>
        </td>
        <td class="table__shrink">
          {{ relative_time(item.timestamp, { date_format: 'short' }) }}
        </td>
        <td><a href="{{ path('user', {username: item.user.username}) }}">{{ item.user.username }}</a></td>
      {% endblock row %}

      {% block footer %}
        {% from '_macros/form.html.twig' import button_row %}
        {{ button_row('action.compare'|trans) }}
      {% endblock footer %}
    {% endembed %}
  </form>
{% endblock body %}

templates/wiki/page.html.twig
{% extends 'wiki/base.html.twig' %}
{% from '_macros/icon.html.twig' import icon %}

{% block title page.latestRevision.title %}

{% block head %}
  <link rel="canonical" href="{{ url('wiki', {path: page.path}) }}">
{% endblock %}

{% block site_nav_active 'places' %}
{% block site_nav_main_menu_active 'wiki' %}
{% block wiki_page_toolbox_active app.request.attributes.get('_route') %}

{% block body %}
  <article class="wiki-article">
    <h1 class="page-heading wiki-article__title">{{ block('title') }}</h1>

    <div class="wiki-article__body">
      {{ page.latestRevision.body|cached_markdown|raw }}
    </div>
  </article>
{% endblock %}

{% block sidebar %}
  {% from '_macros/time.html.twig' import relative_time %}

  <section class="sidebar__section sidebar-card">
    <h1 class="sidebar__title">{{ page.path }}</h1>
      <p>
        {{- 'wiki.last_edited'|trans({
          '%username%': '<a href="%s">%s</a>'|format(
            path('user', {username: page.latestRevision.user.username})|escape,
            page.latestRevision.user.username|escape
          ),
          '%timestamp%': relative_time(page.latestRevision.timestamp, { natural: true }),
        })|raw -}}
      </p>

    {% if page.locked %}
      <p class="wiki-lock-notice">
        <span>{{ icon('lock') }}</span>
        <span>{{ 'wiki.locked_notice'|trans }}</span>
      </p>
    {% endif %}

    {% if is_granted('lock', page) or is_granted('delete', page) %}
      <nav>
        <ul class="flex flex--guttered unlistify">
          {% if is_granted('lock', page) %}
            <li>
              <form action="{{ path(page.locked ? 'wiki_unlock' : 'wiki_lock', {path: page.path}) }}" method="post">
                <input type="hidden" name="token" value="{{ csrf_token('wiki_lock') }}">
                <button class="button button--small">{{ (page.locked ? 'action.unlock' : 'action.lock')|trans }}</button>
              </form>
            </li>
          {% endif %}

          {% if is_granted('delete', page) %}
            <li>
              <form action="{{ path('wiki_delete', { path: page.path }) }}" method="post">
                <input type="hidden" name="token" value="{{ csrf_token('wiki_delete') }}">
                <button class="button button--small js-confirm-wiki-delete">{{ 'action.delete'|trans }}</button>
              </form>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </section>

  <section class="sidebar__section sidebar-card">
    <h1 class="sidebar__title">{{ 'label.toolbox'|trans }}</h1>

    <ul class="no-margin unlistify sidebar__no-padding">
      {% if is_granted('write', page) %}
        <li>
          <a href="{{ path('wiki_edit', {path: page.path}) }}"
             class="menu-item {{ block('wiki_page_toolbox_active') == 'wiki_edit' ? 'menu-item--active' }}">
            {{ 'wiki.edit_page'|trans }}
          </a>
        </li>
      {% endif %}

      <li>
        <a href="{{ path('wiki_history', {path: page.path}) }}"
           class="menu-item {{ block('wiki_page_toolbox_active') == 'wiki_history' ? 'menu-item--active' }}">
          {{- 'wiki.page_history'|trans -}}
        </a>
      </li>
    </ul>
  </section>

  {{ parent() }}
{% endblock %}

templates/wiki/recent.html.twig
{% extends 'wiki/base.html.twig' %}

{% block site_nav_active 'places' %}
{% block site_nav_main_menu_active 'wiki' %}
{% block title 'label.recent_changes'|trans %}

{% block head %}
  {{ include('_includes/meta_pagination.html.twig', { pager: revisions }, with_context=false) }}
{% endblock head %}

{% block body %}
  <h1 class="page-heading">{{ 'label.recent_changes'|trans }}</h1>

  {% embed '_layouts/table_pagination.html.twig' with { items: revisions } %}
    {% block header %}
      <th class="table__shrink">{{ 'label.id'|trans }}</th>
      <th>{{ 'label.title'|trans }}</th>
      <th class="table__shrink">{{ 'label.author'|trans }}</th>
      <th class="table__shrink">{{ 'label.date'|trans }}</th>
    {% endblock header %}

    {% block row %}
      {% from '_macros/time.html.twig' import relative_time %}

      <td class="table__shrink"><a href="{{ path('wiki_revision', {id: item.id}) }}">{{ item.id.hex|slice(0, 8) }}</td>
      <td><a href="{{ path('wiki', {path: item.page.path}) }}">{{ item.page.path }}</a></td>
      <td class="table__shrink"><a href="{{ path('user', {username: item.user.username}) }}">{{ item.user.username }}</a></td>
      <td class="table__shrink">
        {{ relative_time(item.timestamp, { date_format: 'short' }) }}
      </td>
    {% endblock row %}
  {% endembed %}
{% endblock body %}

templates/wiki/revision.html.twig
{% extends 'wiki/page.html.twig' %}

{% block title %}
  {{ 'title.showing_revision'|trans({
    '%revision%': revision.id.hex|slice(0, 8),
    '%path%': '<a href="%s">%s</a>'|format(path('wiki', {path: page.path})|e, page.path|e),
  })|raw }}
{% endblock %}

{% block wiki_page_toolbox_active 'wiki_history' %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <article class="wiki-article">
    <h1 class="wiki-article__title">{{ revision.title }}</h1>

    <div class="wiki-article__body">
      {{ revision.body|cached_markdown|raw }}
    </div>
  </article>

  <hr>

  <h1>{{ 'label.source_code'|trans }}</h1>
  <pre><code class="language-markdown">{{ revision.body }}</code></pre>
{% endblock %}