src/Entity/ForumBan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * Represents a ban or unban action that applies to a user and a forum.
 *
 * @ORM\Entity(repositoryClass="App\Repository\ForumBanRepository")
 */
class ForumBan {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var Uuid
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="Forum", inversedBy="bans")
     *
     * @var Forum
     */
    private $forum;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $reason;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $banned;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $bannedBy;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     *
     * @var \DateTime|null
     */
    private $expiresAt;

    public function __construct(
        Forum $forum,
        User $user,
        string $reason,
        bool $banned,
        User $bannedBy,
        \DateTime $expiresAt = null,
        \DateTime $timestamp = null
    ) {
        if (!$banned && $expiresAt) {
            throw new \DomainException('Unbans cannot have expiry times');
        }

        $this->id = Uuid::uuid4();
        $this->forum = $forum;
        $this->user = $user;
        $this->reason = $reason;
        $this->banned = $banned;
        $this->bannedBy = $bannedBy;
        $this->expiresAt = $expiresAt;

        // since the last ban takes precedence, and because timestamps are used
        // for sorting, we'll use microseconds to hopefully avoid collisions
        $this->timestamp = $timestamp ?:
            \DateTime::createFromFormat('U.u', sprintf('%.6f', microtime(true)));
    }

    public function getId(): Uuid {
        return $this->id;
    }

    public function getForum(): Forum {
        return $this->forum;
    }

    public function getUser(): User {
        return $this->user;
    }

    public function getReason(): string {
        return $this->reason;
    }

    public function isBan(): bool {
        return $this->banned;
    }

    public function getBannedBy(): User {
        return $this->bannedBy;
    }

    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    public function getExpiryTime(): ?\DateTime {
        return $this->expiresAt;
    }

    public function isExpired(): bool {
        if ($this->expiresAt === null) {
            return false;
        }

        return $this->expiresAt < new \DateTime('@'.time());
    }
}

src/Entity/UserBan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserBanRepository")
 */
class UserBan {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var Uuid
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User", inversedBy="bans")
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $reason;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $banned;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $bannedBy;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     *
     * @var \DateTime|null
     */
    private $expiresAt;

    public function __construct(
        User $user,
        string $reason,
        bool $banned,
        User $bannedBy,
        \DateTime $expiresAt = null,
        \DateTime $timestamp = null
    ) {
        if (!$banned && $expiresAt) {
            throw new \DomainException('Unbans cannot have expiry times');
        }

        $this->id = Uuid::uuid4();
        $this->user = $user;
        $this->reason = $reason;
        $this->banned = $banned;
        $this->bannedBy = $bannedBy;
        $this->expiresAt = $expiresAt;
        $this->timestamp = $timestamp ?:
            \DateTime::createFromFormat('U.u', sprintf('%.6f', microtime(true)));
    }

    public function getId(): Uuid {
        return $this->id;
    }

    public function getUser(): User {
        return $this->user;
    }

    public function getReason(): string {
        return $this->reason;
    }

    public function isBan(): bool {
        return $this->banned;
    }

    public function getBannedBy(): User {
        return $this->bannedBy;
    }

    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    public function getExpiresAt(): ?\DateTime {
        return $this->expiresAt;
    }

    public function isExpired(): bool {
        if ($this->expiresAt === null) {
            return false;
        }

        return $this->expiresAt < new \DateTime('@'.time());
    }
}

src/Controller/Api/ForumController.php
<?php

namespace App\Controller\Api;

use App\Controller\AbstractController;
use App\DataObject\ForumData;
use App\Entity\Forum;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/forums", defaults={"_format": "json"}, requirements={"id": "%number_regex%"})
 */
class ForumController extends AbstractController {
    /**
     * @Route("/{id}", methods={"GET"})
     */
    public function read(Forum $forum): Response {
        return $this->json($forum, 200, [], [
            'groups' => ['forum:read', 'abbreviated_relations'],
        ]);
    }

    /**
     * @Route("", methods={"POST"})
     * @IsGranted("create_forum")
     */
    public function create(EntityManagerInterface $em): Response {
        return $this->apiCreate(ForumData::class, [
            'normalization_groups' => ['forum:read', 'abbreviated_relations'],
            'denormalization_groups' => ['forum:create'],
            'validation_groups' => ['create'],
        ], function (ForumData $data) use ($em) {
            $forum = $data->toForum($this->getUser());

            $em->persist($forum);
            $em->flush();

            return $forum;
        });
    }

    /**
     * @Route("/{id}", methods={"PUT"})
     * @IsGranted("moderator", subject="forum")
     */
    public function update(Forum $forum, EntityManagerInterface $em): Response {
        return $this->apiUpdate($forum, ForumData::class, [
            'normalization_groups' => ['forum:read'],
            'denormalization_groups' => ['forum:update'],
            'validation_groups' => ['update'],
        ], function (ForumData $data) use ($forum, $em): void {
            $before = clone $forum;
            $data->updateForum($forum);

            $em->flush();
        });
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\DataObject\ForumData;
use App\Entity\Forum;
use App\Entity\Moderator;
use App\Entity\User;
use App\Form\ConfirmDeletionType;
use App\Form\ForumAppearanceType;
use App\Form\ForumBanType;
use App\Form\ForumType;
use App\Form\Model\ForumBanData;
use App\Form\Model\ModeratorData;
use App\Form\ModeratorType;
use App\Repository\CommentRepository;
use App\Repository\ForumBanRepository;
use App\Repository\ForumCategoryRepository;
use App\Repository\ForumLogEntryRepository;
use App\Repository\ForumRepository;
use App\SubmissionFinder\Criteria;
use App\SubmissionFinder\SubmissionFinder;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Entity("forum", expr="repository.findOneOrRedirectToCanonical(forum_name, 'forum_name')")
 * @Entity("user", expr="repository.findOneOrRedirectToCanonical(username, 'username')")
 */
final class ForumController extends AbstractController {
    /**
     * @var SubmissionFinder
     */
    private $submissionFinder;

    public function __construct(SubmissionFinder $submissionFinder) {
        $this->submissionFinder = $submissionFinder;
    }

    /**
     * Show the front page of a given forum.
     */
    public function front(Forum $forum, ?string $sortBy, string $_format): Response {
        $criteria = (new Criteria($sortBy))
            ->showForums($forum)
            ->stickiesFirst();

        $submissions = $this->submissionFinder->find($criteria);

        return $this->render("forum/forum.$_format.twig", [
            'forum' => $forum,
            'sort_by' => $this->submissionFinder->getSortMode($sortBy),
            'submissions' => $submissions,
        ]);
    }

    public function multi(ForumRepository $fr, string $names, ?string $sortBy): Response {
        $names = array_map(Forum::class.'::normalizeName', explode('+', $names));
        $forums = $fr->findByNormalizedName($names);

        if (!$forums) {
            throw $this->createNotFoundException('no such forums');
        }

        $criteria = (new Criteria($sortBy))
            ->showForums(...$forums);

        $submissions = $this->submissionFinder->find($criteria);

        return $this->render('forum/multi.html.twig', [
            'forums' => $names,
            'sort_by' => $this->submissionFinder->getSortMode($sortBy),
            'submissions' => $submissions,
        ]);
    }

    /**
     * Create a new forum.
     *
     * @IsGranted("ROLE_USER")
     * @IsGranted("create_forum", statusCode=403)
     */
    public function createForum(Request $request, EntityManagerInterface $em): Response {
        $data = new ForumData();

        $form = $this->createForm(ForumType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $forum = $data->toForum($this->getUser());

            $em->persist($forum);
            $em->flush();

            return $this->redirectToRoute('forum', [
                'forum_name' => $forum->getName(),
            ]);
        }

        return $this->render('forum/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("moderator", subject="forum", statusCode=403)
     */
    public function editForum(Request $request, Forum $forum, EntityManagerInterface $em): Response {
        $data = new ForumData($forum);

        $form = $this->createForm(ForumType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateForum($forum);

            $em->flush();
            $this->addFlash('success', 'flash.forum_updated');

            return $this->redirectToRoute('edit_forum', [
                'forum_name' => $forum->getName(),
            ]);
        }

        return $this->render('forum/edit.html.twig', [
            'form' => $form->createView(),
            'forum' => $forum,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @IsGranted("delete", subject="forum", statusCode=403)
     */
    public function delete(Request $request, Forum $forum, EntityManagerInterface $em): Response {
        $form = $this->createForm(ConfirmDeletionType::class, null, [
            'name' => $forum->getName(),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->remove($forum);
            $em->flush();

            $this->addFlash('notice', 'flash.forum_deleted');

            return $this->redirectToRoute('front');
        }

        return $this->render('forum/delete.html.twig', [
            'form' => $form->createView(),
            'forum' => $forum,
        ]);
    }

    public function comments(CommentRepository $comments, Forum $forum): Response {
        return $this->render('forum/comments.html.twig', [
            'comments' => $comments->findPaginatedByForum($forum),
            'forum' => $forum,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     */
    public function subscribe(Request $request, EntityManagerInterface $em, Forum $forum, bool $subscribe, string $_format): Response {
        $this->validateCsrf('subscribe', $request->request->get('token'));

        if ($subscribe) {
            $forum->subscribe($this->getUser());
        } else {
            $forum->unsubscribe($this->getUser());
        }

        $em->flush();

        if ($_format === 'json') {
            return $this->json(['subscribed' => $subscribe]);
        }

        if ($request->headers->has('Referer')) {
            return $this->redirect($request->headers->get('Referer'));
        }

        return $this->redirectToRoute('forum', ['forum_name' => $forum->getName()]);
    }

    public function list(ForumRepository $repository, int $page, string $sortBy): Response {
        return $this->render('forum/list.html.twig', [
            'forums' => $repository->findForumsByPage($page, $sortBy),
            'sortBy' => $sortBy,
        ]);
    }

    public function listCategories(ForumCategoryRepository $fcr, ForumRepository $fr): Response {
        $forumCategories = $fcr->findBy([], ['name' => 'ASC']);
        $uncategorizedForums = $fr->findBy(['category' => null], ['normalizedName' => 'ASC']);

        return $this->render('forum/list_by_category.html.twig', [
            'forum_categories' => $forumCategories,
            'uncategorized_forums' => $uncategorizedForums,
        ]);
    }

    /**
     * Show a list of forum moderators.
     */
    public function moderators(Forum $forum, int $page): Response {
        return $this->render('forum/moderators.html.twig', [
            'forum' => $forum,
            'moderators' => $forum->getPaginatedModerators($page),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("ROLE_ADMIN", statusCode=403)
     */
    public function addModerator(EntityManagerInterface $em, Forum $forum, Request $request): Response {
        $data = new ModeratorData($forum);
        $form = $this->createForm(ModeratorType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($data->toModerator());
            $em->flush();

            $this->addFlash('success', 'flash.forum_moderator_added');

            return $this->redirectToRoute('forum_moderators', [
                'forum_name' => $forum->getName(),
            ]);
        }

        return $this->render('forum/add_moderator.html.twig', [
            'form' => $form->createView(),
            'forum' => $forum,
        ]);
    }

    /**
     * @Entity("moderator", expr="repository.findOneBy({'forum': forum, 'id': moderator_id})")
     * @IsGranted("ROLE_USER")
     * @IsGranted("remove", subject="moderator", statusCode=403)
     */
    public function removeModerator(EntityManagerInterface $em, Forum $forum, Request $request, Moderator $moderator): Response {
        $this->validateCsrf('remove_moderator', $request->request->get('token'));

        $em->remove($moderator);
        $em->flush();

        $this->addFlash('success', 'flash.user_unmodded');

        return $this->redirectToRoute('forum_moderators', [
            'forum_name' => $forum->getName(),
        ]);
    }

    public function moderationLog(Forum $forum, int $page): Response {
        return $this->render('forum/moderation_log.html.twig', [
            'forum' => $forum,
            'logs' => $forum->getPaginatedLogEntries($page),
        ]);
    }

    public function globalModerationLog(ForumLogEntryRepository $forumLogs, int $page): Response {
        return $this->render('forum/global_moderation_log.html.twig', [
            'logs' => $forumLogs->findAllPaginated($page),
        ]);
    }

    /**
     * Alter a forum's appearance.
     *
     * @IsGranted("ROLE_USER")
     * @IsGranted("moderator", subject="forum", statusCode=403)
     */
    public function appearance(Forum $forum, Request $request, EntityManagerInterface $em): Response {
        $data = new ForumData($forum);

        $form = $this->createForm(ForumAppearanceType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateForum($forum);

            $em->flush();

            return $this->redirectToRoute('forum_appearance', [
                'forum_name' => $forum->getName(),
            ]);
        }

        return $this->render('forum/appearance.html.twig', [
            'form' => $form->createView(),
            'forum' => $forum,
        ]);
    }

    public function bans(Forum $forum, ForumBanRepository $banRepository, int $page = 1): Response {

templates/forum/_list_macros.html.twig
{% macro header() %}
  <h1 class="no-margin">{{ 'forum_list.page_title'|trans }}</h1>
{% endmacro header %}

{% macro forum_list_tabs() %}
  <ul class="unlistify flex no-margin">
    {% with { active: app.request.attributes.get('_route') == 'forum_list' } %}
      <li>
        <a href="{{ path('forum_list') }}" class="tab {{ active ? 'tab--active' }}">
          {{- 'forum_list.list_view'|trans -}}
        </a>
      </li>
    {% endwith %}
    {% with { active: app.request.attributes.get('_route') == 'forums_by_category' } %}
      <li>
        <a href="{{ path('forums_by_category') }}" class="tab {{ active ? 'tab--active' }}">
          {{- 'forum_list.category_view'|trans -}}
        </a>
      </li>
    {% endwith %}
  </ul>
{% endmacro forum_list_tabs %}

{% macro create_forum() %}
  {% if is_granted('create_forum') %}
    <div>
      <a href="{{ path('create_forum') }}" class="button">{{ 'forum.create'|trans }}</a>
    </div>
  {% endif %}
{% endmacro create_forum %}

templates/forum/add_moderator.html.twig
{% extends 'forum/base.html.twig' %}
{% from '_macros/form.html.twig' import button_row %}

{% block title block('html_title')|striptags %}

{% block body %}
  <h1 class="page-heading">
    {% block html_title %}
      {{- 'add_moderator.title'|trans({
        '%forum%': '<a href="%s">/f/%s</a>'|format(
          path('forum', { forum_name: forum.name })|e,
          forum.name|e
        ),
      })|raw -}}
    {% endblock html_title %}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.user) }}

    {{ button_row('forum.add_as_moderator'|trans) }}
  {{ form_end(form) }}
{% endblock body %}

templates/forum/appearance.html.twig
{% extends 'forum/base.html.twig' %}

{% block title 'title.forum_appearance'|trans({'%forum%': '/f/%s'|format(forum.name)}) %}

{% form_theme form '_forms/aligned_form_theme.html.twig' %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.forum_appearance'|trans({'%forum%': '<a href="%s">/f/%s</a>'|format(
      path('forum', {forum_name: forum.name})|escape,
      forum.name|escape
    )})|raw }}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.suggestedTheme) }}

    {% if form.backgroundImage is defined %}
      {{ form_widget(form.backgroundImage) }}
    {% endif %}

    <div class="form-row form-row--single-line">
      <div class="form-row__align" aria-hidden="true"></div>
      <button class="button">{{ 'action.save'|trans }}</button>
    </div>
  {{ form_end(form) }}
{% endblock body %}

templates/forum/ban_history.html.twig
{% extends 'forum/base.html.twig' %}

{% block title 'title.showing_ban_history_for_user_in_forum'|trans({
  '%user%': '/u/'~user.username,
  '%forum%': '/f/'~forum.name,
}) %}

{% block head %}
  {{ parent() }}
  {{ include('_includes/meta_pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock head %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {% embed '_layouts/table_pagination.html.twig' with { items: bans } %}
    {% block header %}
      <th class="table__shrink">{{ 'label.action'|trans }}</th>
      <th>{{ 'label.reason'|trans }}</th>
      <th class="table__shrink">{{ 'label.banned'|trans }}</th>
      <th class="table__shrink">{{ 'label.expires'|trans }}</th>
    {% endblock header %}

    {% block row %}
      {% from '_macros/time.html.twig' import relative_time %}
      <td class="table__shrink">{{ (item.ban ? 'label.ban' : 'label.unban')|trans }}</td>
      <td>{{ item.reason }}</td>
      <td class="table__shrink">
        {{ relative_time(item.timestamp, { date_format: 'short', time_format: 'none' }) }}
      </td>
      <td class="table__shrink">
        {% if item.expiryTime %}
          {{ relative_time(item.expiryTime, { date_format: 'short' }) }}
        {% else %}
          <small class="fg-muted text-sm">{{ 'label.never'|trans }}</small>
        {% endif %}
      </td>
    {% endblock row %}
  {% endembed %}
{% endblock body %}

templates/forum/base.html.twig
{% extends 'base.html.twig' %}
{% from '_macros/icon.html.twig' import icon %}
{% from '_macros/time.html.twig' import relative_time %}

{% block forum_toolbox_active app.request.attributes.get('_route') %}

{% block feed %}
  {{ parent() }}
  <link rel="alternate" type="application/atom+xml" href="{{ path('forum', { forum_name: forum.name, sortBy: 'new', _format: 'atom' }) }}" title="/f/{{ forum.name }}">
{% endblock feed %}

{% block theme_css %}
  {% set theme = (app.user.showCustomStylesheets ?? true) ? forum.suggestedTheme %}
  {% if theme %}
    {{ encore_entry_link_tags(theme_entrypoint(theme.configKey)) }}
  {% else %}
    {{ parent() }}
  {% endif %}

  {{ include('_includes/background_image.html.twig', { entity: forum }, with_context=false) }}
{% endblock theme_css %}

{% block sidebar %}
  <section class="sidebar__section sidebar-card">
    <h1 class="sidebar__title forum-title break-text">
      <a href="{{ path('forum', {forum_name: forum.name}) }}">{{ forum.title }}</a>
    </h1>

    {% if is_granted('ROLE_USER') %}
      {% from 'forum/_macros.html.twig' import subscribe_button %}
      {% set subscribed = forum.subscribed(app.user) %}
      <form action="{{ path(subscribed ? 'unsubscribe' : 'subscribe', {forum_name: forum.name}) }}"
            method="POST"
            class="form subscribe-form"
            data-forum="{{ forum.name }}">
        <input type="hidden" name="token" value="{{ csrf_token('subscribe') }}">

        <div class="form__row">
          {{ subscribe_button(forum, subscribed, false) }}
        </div>
      </form>
    {% endif %}

    {% if forum.sidebar is not empty %}
      <div class="forum-sidebar-content break-text">
        {{- forum.sidebar|cached_markdown|raw -}}
      </div>

      <hr>
    {% endif %}

    <ul class="text-sm unlistify">
      <li class="fg-muted">
        {{- 'forum.created_on'|trans({
          '%timestamp%': relative_time(forum.created, { time_format: 'none' }),
        })|raw -}}
      </li>

      <li>
        <a href="{{ path('forum', { forum_name: forum.name, _format: 'atom', sortBy: 'new' }) }}"
           rel="alternate"
           type="application/atom+xml"
           class="no-underline">
          {{- icon('rss-squared', '', 'fg-orange') }}
          <span class="no-underline__exempt">{{ 'action.subscribe_via_rss'|trans -}}</span>
        </a>
      </li>
    </ul>
  </section>

  {% if is_granted('ROLE_USER') %}
    {% set is_hidden = app.user.hidingForum(forum) %}
    <details class="sidebar__section sidebar-card">
      <summary class="sidebar__title">{{ 'heading.hide_this_forum'|trans }}</summary>

      <p class="fg-muted text-md">{{ 'help.hidden_forums'|trans }}</p>

      <form action="{{ path(is_hidden ? 'unhide_forum' : 'hide_forum', {username: app.user.username, forum: forum.id}) }}" method="POST">
        <input type="hidden" name="token" value="{{ csrf_token('hide_forum') }}">

        <p>
          <button class="button button--secondary" title="">
            {{ is_hidden ? 'action.unhide'|trans : 'action.hide'|trans }}
          </button>
        </p>
      </form>
    </details>
  {% endif %}

  <section class="sidebar__section sidebar-card">
    <h1 class="sidebar__title">{{ 'label.toolbox'|trans }}</h1>

    {% set toolbox_items = {
      ('nav.bans'|trans): {
        route: 'forum_bans',
      },
      ('nav.moderation_log'|trans): {
        route: 'moderation_log',
      },
      ('forum.edit'|trans): {
        route: 'edit_forum',
        condition: is_granted('moderator', forum),
      },
      ('nav.appearance'|trans): {
        route: 'forum_appearance',
        condition: is_granted('moderator', forum),
      },
      ('nav.delete_forum'|trans): {
        route: 'delete_forum',
        condition: is_granted('delete', forum),
      },
    } %}

    <ul class="no-margin unlistify sidebar__no-padding">
      {% for label in toolbox_items|keys|sort|filter(label => toolbox_items[label].condition ?? true) %}
        {% set item = toolbox_items[label] %}
        <li>
          <a href="{{ path(item.route, { forum_name: forum.name }) }}"
             class="menu-item {{ block('forum_toolbox_active') == item.route ? 'menu-item--active' }}">
            {{- label -}}
          </a>
        </li>
      {% endfor %}
    </ul>
  </section>

  {% if forum.moderators is not empty or is_granted('ROLE_ADMIN') %}
    <section class="sidebar__section sidebar-card">
      <div class="flex flex--guttered">
        <h1 class="sidebar__title flex__grow">
          {{- 'forum.moderators'|trans -}}
        </h1>

        {% if is_granted('ROLE_ADMIN') %}
          <div>
            <a href="{{ path('add_moderator', { forum_name: forum.name }) }}"
               class="button button--small button--secondary text-sm"
               aria-label="{{ 'forum.add_moderator'|trans }}">
              {{ 'action.add'|trans }}
            </a>
          </div>
        {% endif %}
      </div>

      {% if forum.moderators is not empty %}
        <ul class="unlistify flex flex--guttered flex--slim-gutters">
          {% for moderator in forum.moderators %}
            <li>
              <a href="{{ path('user', {username: moderator.user.username}) }}"
                 class="button button--secondary button--small">
                {{- moderator.user.username -}}
              </a>
            </li>
          {% endfor %}
        </ul>

        <p>
          <a href="{{ path('forum_moderators', { forum_name: forum.name }) }}">
            {{- 'action.see_full_list'|trans -}}
          </a>
        </p>
      {% else %}
        <p class="fg-muted text-sm">{{ 'flash.no_moderators'|trans }}</p>
      {% endif %}
    </section>
  {% endif %}
{% endblock sidebar %}

templates/forum/delete.html.twig
{% extends 'forum/base.html.twig' %}
{% from '_macros/alert.html.twig' import alert %}
{% from '_macros/form.html.twig' import button_row %}

{% block title 'title.delete_forum'|trans({'%forum%': '/f/%s'|format(forum.name)}) %}

{% block body %}
  <h1 class="page-heading">
    {{- 'title.delete_forum'|trans({'%forum%': '<a href="%s">/f/%s</a>'|format(
      path('forum', {forum_name: forum.name})|escape,
      forum.name|escape
      )})|raw
    -}}
  </h1>

  {{ alert('help.delete_forum_warning'|trans, 'warn') }}

  {{ form_start(form) }}
    {{ form_row(form.name, { label: 'label.confirm_forum_name'|trans }) }}

    {{ form_row(form.confirm, { label: 'label.delete_forum_confirmation'|trans }) }}

    {{ button_row('forum.delete'|trans) }}
  {{ form_end(form) }}
{% endblock %}